### ISSUE TITLE
Parallel Implementation

### ISSUE THREAD

**Issue by shivin9** [JuliaArrays/MappedArrays.jl#11]
I think it will be helpful if this package can support parallel implementation of the mappings.

**Comment by timholy** [comment]
Since it's lazy, you can create the mapping on a 1TB array in a microsecond, so there's no need to parallelize construction.

Moreover, you can apply this to any array type, including distributed arrays. It might make some sense to "internalize" the mapping so that the outer container is distributed, but that would have to be done on a case-by-case basis for specific parallel array types.
