### ISSUE TITLE
`of_eltype` does not work for arrays of eltype Any (?)

### ISSUE THREAD

**Issue by lassepe** [JuliaArrays/MappedArrays.jl#47]
```julia
julia> import MappedArrays

julia> a = Any[1,2,3]
3-element Vector{Any}:
 1
 2
 3

julia> b = MappedArrays.of_eltype(Int, a)
3-element mappedarray(x->MappedArrays.convert($(Expr(:static_parameter, 1)), x), y->MappedArrays.convert($(Expr(:static_parameter, 1)), y), ::Vector{Any}) with eltype Any:
 1
 2
 3

julia> eltype(b)
Any
```

**Comment by johnnychen94** [comment]
The reason behind this is the type of `x->convert(Int, x)` is not inferrable:

```julia
julia> Base.return_types(x->convert(Int, x), (Any,))
1-element Vector{Any}:
 Any
```

https://github.com/JuliaArrays/MappedArrays.jl/blob/9fbda813db398056f6956872207544fd2e3fd77e/src/MappedArrays.jl#L116

I don't know how to propagate the type information to `Base.return_types`; a "bad" workaround is:

```julia
of_eltype(::Type{T}, data::AbstractArray{S}) where {S, T<:Number} = mappedarray(T, y->convert(S, y), data)
```

It's bad because it's not very extensible to other cases.

**Comment by lassepe** [comment]
Wow, I was not aware that convert is not inferrable. I would have assumed that this should always be trivially inferrable because it has the return type as an input?

**Comment by cstjean** [comment]
`@code_warntype` evaluates the arguments of the function. It's assessing `f(1.0)`...
